theme: jekyll-theme-cayman

# Basic
title: LILIAN
subtitle: 心灵之窗
description: 经过了这么多年，我们终于看清了自己
# 头像里面的标题
avatarTitle: dearLilian
# 头像里面的描述
avatarDesc: 数据挖掘 / 机器学习
url: "http://lilian.info"

# Comment
comment:
    # disqus: lilian
    duoshuo: lilian 

# Social
social:
    weibo: 2344041987
    github: dearLilian
    weixin: lwb116xhn
    #gsite: liliandreamworld
    csdn: lilianforever
    # twitter: 
    mail: liwenbao930116@gmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: e572ae9801b3a18891f123796b889f77

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-88738012-1   
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/dearLilian/dearLilian.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 留言板, description: messages, url: '/messages'}   #这是我的模板新增的。如果你使用的是baixin的模板，则删除这一行
    - {title: 关于我, description: about, url: '/about'}      

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"